
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 05 10:45:09 CEST 2013
//----------------------------------------------------

package analyse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int UMINUS = 10;
  public static final int MOD = 9;
  public static final int MULT = 4;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ENTIER = 11;
  public static final int error = 1;
  public static final int PAR_G = 6;
  public static final int MOINS = 3;
  public static final int PAR_D = 7;
  public static final int POINT_VIRGULE = 8;
}

